# Generated by Django 4.2.5 on 2023-11-14 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient", old_name="econtact", new_name="contact",
        ),
        migrations.RenameField(
            model_name="patient", old_name="eemail", new_name="email",
        ),
        migrations.RenameField(
            model_name="patient", old_name="ename", new_name="name",
        ),
        migrations.RemoveField(model_name="patient", name="eid",),
        migrations.AddField(
            model_name="patient",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patient",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
